# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-27 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=30, unique=True, verbose_name='\u4e3b\u673a\u540d')),
                ('lease_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 27, 16, 43, 5, 242000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
