# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-14 03:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 14, 11, 38, 41, 437000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
