# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-19 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 19, 16, 33, 56, 233000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
