# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-20 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161219_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostlist',
            name='inner_ip',
            field=models.CharField(max_length=20, null=True, verbose_name='\u5185\u7f51IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 20, 15, 42, 32, 751000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
