# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-15 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_idc_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='idc',
            name='jumper_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='\u8df3\u677f\u673aIP'),
        ),
        migrations.AddField(
            model_name='idc',
            name='salt_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='\u7ba1\u7406\u673a\u5668IP'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 15, 14, 31, 22, 211000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
