# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-27 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161227_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='hostname',
        ),
        migrations.AddField(
            model_name='lease',
            name='hostList',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='app.HostList'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 27, 17, 13, 29, 307000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
