# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 06:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161215_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 17, 14, 44, 44, 615000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
