# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 04:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161220_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='group_name',
            field=models.CharField(max_length=50, null=True, verbose_name='\u7ec4\u540d'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 22, 12, 36, 19, 759000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
