# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161222_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u4e3b\u673aId'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 22, 15, 26, 17, 155000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
