# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161217_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hostlist',
            name='bianhao',
        ),
        migrations.RemoveField(
            model_name='hostlist',
            name='group',
        ),
        migrations.RemoveField(
            model_name='hostlist',
            name='idc_name',
        ),
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default=b'', max_length=50, unique=True, verbose_name=b'\xe7\xbb\x84\xe5\x90\x8d'),
        ),
        migrations.AddField(
            model_name='group',
            name='idc_name',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u6240\u5c5e\u673a\u623f'),
        ),
        migrations.AddField(
            model_name='hostlist',
            name='group_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name=b'\xe7\xbb\x84\xe5\x90\x8d'),
        ),
        migrations.AddField(
            model_name='hostlist',
            name='nick_name',
            field=models.CharField(max_length=30, null=True, verbose_name='\u4e3b\u673a\u522b\u540d'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=70, null=True, verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 17, 15, 24, 29, 845000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
