# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-23 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161222_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='hostname',
            field=models.CharField(max_length=30, unique=True, verbose_name='\u4e3b\u673a\u540d'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 23, 16, 3, 42, 513000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
