# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-28 02:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161228_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostrequest',
            name='lease_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 28, 10, 21, 52, 541000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='lease_time',
            field=models.IntegerField(default=30),
        ),
    ]
