# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 07:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161217_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.AddField(
            model_name='group',
            name='remark',
            field=models.CharField(max_length=70, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 17, 15, 53, 31, 434000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
