# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-23 09:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161223_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 23, 17, 14, 16, 53000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
