# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-30 02:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161228_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostrequest',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 30, 10, 57, 53, 732000), verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='hostrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u7533\u8bf7Id'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 30, 10, 57, 53, 728000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
