# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-17 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161217_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='remark',
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 17, 16, 34, 47, 138000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
