# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-26 09:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161223_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromuser', models.CharField(max_length=50)),
                ('touser', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=3000)),
                ('deal', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 26, 17, 43, 41, 602000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
