# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-26 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161226_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 26, 17, 48, 24, 597000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
