# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 03:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161217_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='remark',
            field=models.CharField(default=b'', max_length=50, null=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 18, 11, 26, 30, 558000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
