# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-26 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161226_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='fromuser',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='touser',
            new_name='to_user',
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 26, 17, 50, 32, 405000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
