# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 05:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161218_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 18, 13, 17, 53, 619000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='\u673a\u623fId'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='idc_name',
            field=models.CharField(max_length=40, unique=True, verbose_name='\u673a\u623f\u540d\u79f0'),
        ),
    ]
