# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-03 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161230_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='jumper_ip',
        ),
        migrations.AlterField(
            model_name='hostrequest',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2017, 1, 3, 19, 15, 25, 369000), verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2017, 1, 3, 19, 15, 25, 365000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
