# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161218_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostlist',
            name='application',
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 18, 14, 15, 46, 594000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
