# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-03 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170103_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idc',
            name='salt_ip',
        ),
        migrations.AlterField(
            model_name='hostrequest',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2017, 1, 3, 19, 17, 20, 595000), verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2017, 1, 3, 19, 17, 20, 591000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
