# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-04 03:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170103_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostrequest',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2017, 1, 4, 11, 31, 36, 651000), verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2017, 1, 4, 11, 31, 36, 648000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='hostname',
            field=models.CharField(default=b'', max_length=30, verbose_name='\u4e3b\u673a\u540d'),
        ),
    ]
