# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-04 06:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170104_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lease',
        ),
        migrations.AlterField(
            model_name='hostrequest',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2017, 1, 4, 14, 57, 38, 718000), verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2017, 1, 4, 14, 57, 38, 715000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
