# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-04 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u7533\u8bf7Id')),
                ('username', models.CharField(max_length=50)),
                ('hostname', models.CharField(default='', max_length=30, verbose_name='\u4e3b\u673a\u540d')),
                ('nick_name', models.CharField(max_length=30, null=True, verbose_name='\u4e3b\u673a\u522b\u540d')),
                ('lease_time', models.IntegerField(default=30)),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.DateField(default=datetime.datetime(2017, 1, 4, 16, 28, 48, 879000), verbose_name='\u5f00\u59cb\u65f6\u95f4')),
            ],
        ),
    ]
