# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-28 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20161228_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 28, 16, 52, 0, 758000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u90ae\u4ef6Id'),
        ),
    ]
