# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-29 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20161229_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='status',
        ),
        migrations.AddField(
            model_name='usermail',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='email',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 29, 16, 59, 50, 914000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
