# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-30 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20161229_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2016, 12, 30, 14, 4, 58, 265000), verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
